[package]
name = "mdp"
version = "0.0.1"
authors = ["Ben Zhang <benzh@cs.berkeley.edu>"]

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"
termios = "0.2.2"
pulldown-cmark = "0.0.8"
termion = "1.1.1"
textwrap = "0.8"

[[bin]]
doc = false
name = "main"
path = "src/main.rs"
