[package]
name = "mdp"
version = "0.0.1"
authors = ["Ben Zhang <benzh@cs.berkeley.edu>"]

[dependencies]
chan-signal="0.3.1"
env_logger = "*"
log = "*"
pulldown-cmark = "0.0.8"
structopt = "0.1.0"
structopt-derive = "0.1.0"
termion = "1.1.1"
termios = "0.2.2"
textwrap = "0.8"
chan = "0.1.19"
